// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using contractWhist2.Data;

namespace contractWhist2.Migrations
{
    [DbContext(typeof(whistContext))]
    [Migration("20191107160353_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("contractWhist2.Models.card", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("fullname")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("suit")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("valueInSuit")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.ToTable("card");
                });

            modelBuilder.Entity("contractWhist2.Models.game", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("crdate")
                        .HasColumnType("datetime2");

                    b.HasKey("id");

                    b.ToTable("game");
                });

            modelBuilder.Entity("contractWhist2.Models.gameRound", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("gameid")
                        .HasColumnType("int");

                    b.Property<int>("numCards")
                        .HasColumnType("int");

                    b.Property<int>("roundNumber")
                        .HasColumnType("int");

                    b.Property<int?>("trumpCardsid")
                        .HasColumnType("int");

                    b.Property<string>("trumpSuit")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.HasIndex("gameid")
                        .IsUnique();

                    b.HasIndex("trumpCardsid");

                    b.ToTable("gameRound");
                });

            modelBuilder.Entity("contractWhist2.Models.playerRound", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("gameId")
                        .HasColumnType("int");

                    b.Property<int>("gamePoints")
                        .HasColumnType("int");

                    b.Property<int>("playerId")
                        .HasColumnType("int");

                    b.Property<int>("roundId")
                        .HasColumnType("int");

                    b.Property<int>("roundPoints")
                        .HasColumnType("int");

                    b.Property<int>("target")
                        .HasColumnType("int");

                    b.Property<int>("tricksWon")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.ToTable("playerRound");
                });

            modelBuilder.Entity("contractWhist2.Models.playerRoundCard", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("cardPlayed")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("playerId")
                        .HasColumnType("int");

                    b.Property<int?>("playerRoundid")
                        .HasColumnType("int");

                    b.Property<int>("prID")
                        .HasColumnType("int");

                    b.Property<int>("roundid")
                        .HasColumnType("int");

                    b.Property<int?>("thisCardid")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("playerRoundid");

                    b.HasIndex("thisCardid");

                    b.ToTable("playerRoundCard");
                });

            modelBuilder.Entity("contractWhist2.Models.gameRound", b =>
                {
                    b.HasOne("contractWhist2.Models.game", null)
                        .WithOne("currentRound")
                        .HasForeignKey("contractWhist2.Models.gameRound", "gameid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("contractWhist2.Models.card", "trumpCards")
                        .WithMany()
                        .HasForeignKey("trumpCardsid");
                });

            modelBuilder.Entity("contractWhist2.Models.playerRoundCard", b =>
                {
                    b.HasOne("contractWhist2.Models.playerRound", null)
                        .WithMany("pCards")
                        .HasForeignKey("playerRoundid");

                    b.HasOne("contractWhist2.Models.card", "thisCard")
                        .WithMany()
                        .HasForeignKey("thisCardid");
                });
#pragma warning restore 612, 618
        }
    }
}
